version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/usr/src/app
      # Exclude node_modules from being overwritten by the host
      - /usr/src/app/node_modules
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - redis
    networks:
      - astrbot-net

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - astrbot-net

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - astrbot-net

networks:
  astrbot-net:
    driver: bridge

volumes:
  postgres-data: