# Use the official Node.js 20 image as a base
FROM node:20-alpine

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package.json package-lock.json ./

# Install project dependencies
RUN npm install --frozen-lockfile

# Copy the rest of the application's source code
# This will be overwritten by the volume mount in docker-compose.dev.yml,
# but it's good practice to have it here for standalone image building.
COPY . .

# Expose the port the app runs on
EXPOSE 3001

# The command to start the app in development mode with hot-reloading
CMD ["npm", "run", "start:dev"]