# .github/workflows/deploy.yml

name: Deploy to Server

on:
  push:
    branches:
      - main  # 或者您的主分支名，例如 master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT || 22 }}
          script: |
            cd /path/to/your/project  # 请替换为您的项目在服务器上的路径
            git pull
            docker-compose down
            docker-compose up --build -d
            echo "Deployment successful!"
